version: '3'

# Define services
services:
  # Database Service (MySQL)
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    restart: always
    volumes:
      - ~/.laradock/data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maindb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    ports:
      - "4407:3306"
    networks:
      dev_net:
          
networks:
  dev_net:      